name: CI
on: [ push, pull_request ]

jobs:
  lint-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python + Poetry
        uses: moneymeets/action-setup-python-poetry@master

      - name: Run linter
        run: |
          find . -name '*.py' | xargs poetry run add-trailing-comma --py36-plus
          poetry run flake8

      - name: Run tests
        run: poetry run pytest --cov --cov-fail-under=90
