name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish-package:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/action-setup-python-poetry@master

      - name: Publish package
        run: |
          sed -i -e "s/1+SNAPSHOT/0.$(date +"%Y%m%d%H%M")+$(git rev-parse --verify --short=7 HEAD)/" pyproject.toml
          poetry publish --build
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }}
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
